[package]
name = "breadferris"
version = "0.1.0"
authors = ["fn79"]
license = "MIT"
edition = "2018"

[dependencies]
tracing = "0.1.23"
tracing-subscriber = "0.2"
tempdir = "*"

[dependencies.tokio]
version = "1.0"
features = ["macros", "signal", "rt-multi-thread"]

[dependencies.serenity]
features = ["cache", "framework", "standard_framework", "rustls_backend"]
